### ISSUE TITLE
Cleaning up view when it's offscreen

### ISSUE THREAD

**Issue by pieterclaerhout** [Blue-Rocket/BRScroller#2]
Hi there,

what would be the best way to properly recycle a reusable view when it goes off the screen? There are the willLeavePage: and didLeavePage: delegate methods, but none of them is giving me a reference to the reusable view.

The scenario is that we want to use this to show separate pages containing movies. However, we need to stop them and cleanup the movie when it goes offscreen...

Thanks,

pieter

**Comment by msqr** [comment]
Hi Pieter,

You should be able to call `[scroller reusablePageViewAtIndex:index]` from within the `scroller:willLeavePage:` delegate method to get the reusable page view in question, and clean up the movie there.
